routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $threads = App\Thread::paginate(15);
    return view('welcome', compact('threads'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/thread', 'ThreadController');

Route::resource('/comment', 'CommentController', ['only' => ['update', 'destroy']]);

Route::post('/comment/create/{thread}', 'CommentController@addThreadComment')->name('threadcomment.store');

Route::post('/reply/create/{comment}', 'CommentController@addReplyComment')->name('replycomment.store');

Route::post('mark/as/solution', 'ThreadController@markAsSolution')->name('markAsSolution');

Route::post('comment/like', 'LikeController@toggleLike')->name('toggleLike');

Route::get('/user/profile/{user}', 'UserProfileController@index')->name('user_profile');

Route::get('/markAsRead', function (){
    auth()->user()->unreadNotifications->markAsRead();
});

resources/views/layouts/includes/categories.blade.php
<div class="col-md-3">

    @yield('user_profile')

    <ul class="list-group">
        <a href="{{ route('thread.index') }}" class="list-group-item">
            <span class="badge">14</span>
            All Thread
        </a>

        @foreach($tags as $tag)

            <a href="{{ route('thread.index', ['tags'=>$tag->id]) }}" class="list-group-item">
                <span class="badge">2</span>
                {{ $tag->name }}
            </a>

        @endforeach

    </ul>

</div>

resources/views/layouts/includes/error.blade.php
@if(count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if ($errors->has('g-recaptcha-response'))
    <span class="help-block">
        <strong>{{ $errors->first('g-recaptcha-response') }}</strong>
    </span>
@endif

resources/views/layouts/includes/navbar.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                    </li>
                @else
                    <li class="nav-item dropdown" id="markasread" onclick="markNotificationAsRead({{ count(auth()->user()->unreadNotifications) }})">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            Notifications <span class="badge badge-primary">
                                {{ count(auth()->user()->unreadNotifications) }}
                            </span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            @forelse(auth()->user()->unreadNotifications as $notification)

                                @include('layouts.includes.notification.'.snake_case(class_basename($notification->type)))
                                    {{--{{ snake_case(class_basename($notification->type)) }}--}}
                                @empty
                                <a href="#">No Unread Notification</a>
                            @endforelse
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <a class="dropdown-item" href="{{ route('user_profile', auth()->user()) }}">
                                My Profile
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/includes/success.blade.php
@if(session('message'))
    <div class="alert alert-success">
        {{ session('message') }}
    </div>
@endif