routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $threads = App\Thread::paginate(15);
    return view('welcome', compact('threads'));
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/thread', 'ThreadController');

Route::resource('/comment', 'CommentController', ['only' => ['update', 'destroy']]);

Route::post('/comment/create/{thread}', 'CommentController@addThreadComment')->name('threadcomment.store');

Route::post('/reply/create/{comment}', 'CommentController@addReplyComment')->name('replycomment.store');

Route::post('mark/as/solution', 'ThreadController@markAsSolution')->name('markAsSolution');

Route::post('comment/like', 'LikeController@toggleLike')->name('toggleLike');

Route::get('/user/profile/{user}', 'UserProfileController@index')->name('user_profile');

Route::get('/markAsRead', function (){
    auth()->user()->unreadNotifications->markAsRead();
});

app/Thread.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use CommentableTrait, RecordsFeed;

    protected $fillable=['subject', 'type', 'thread', 'user_id'];

    public static function boot()
    {
        parent::boot();

//        static::created(function($thread){
//            $thread->recordFeed('created');
//        });

//        static::created(function($thread){
//            $thread->recordFeed('deleted');
//        });
    }

//    protected function recordFeed($event)
//    {
//        $this->feeds()->create([
//            'user_id' => auth()->id(),
//            'type' => $event.'_'.strtolower(class_basename($this)) //created_thread
//        ]);
//    }
//
//    public function feeds()
//    {
//        return $this->morphMany(Feed::class, 'feedable');
//    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }

}

app/Http/Controllers/ThreadController.php
<?php

namespace App\Http\Controllers;

use App\Thread;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class ThreadController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->has('tags')){
            $tag = Tag::find($request->tags);
            $threads = $tag->threads;
        }else{
            $threads = Thread::paginate(15);
        }

        return view('thread.index', compact('threads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('thread.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'subject' => 'required|min:10',
           'tags' => 'required',
           'thread' => 'required|min:10',
//            'g-recaptcha-response' => 'required|captcha'
        ]);

        $thread = auth()->user()->threads()->create($request->all());

        $thread->tags()->attach($request->tags);

        return back()->withMessage('Thread Created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function show(Thread $thread)
    {
        return view('thread.single', compact('thread'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function edit(Thread $thread)
    {
        return view('thread.edit', compact('thread'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Thread $thread)
    {
//        if (auth()->user()->id !== $thread->user_id){
//            abort( 401, "unauthorized");
//        }

        $this->authorize('update', $thread);

        $this->validate($request, [
            'subject' => 'required|min:10',
            'type' => 'required',
            'thread' => 'required|min:20'
        ]);

        $thread->update($request->all());

        return redirect()->route('thread.show', $thread->id)->withMessage('Thread Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Thread  $thread
     * @return \Illuminate\Http\Response
     */
    public function destroy(Thread $thread)
    {
        if (auth()->user()->id !== $thread->user_id){
            abort( 401, "unauthorized");
        }

        $thread->delete();
        return redirect()->route('thread.index')->withMessage('Thread Deleted');

    }

    public function markAsSolution()
    {

        $solutionId = Input::get('solutionId');
        $threadId = Input::get('threadId');
        $thread = Thread::find($threadId);
        $thread->solution = $solutionId;

        if ($thread->save()){

            if (request()->ajax()){
                return response()->json(['status' => 'success', 'message' => 'marked as solution']);
            }
            return back()->withMessage('Marked as solution');
        }

    }

}

resources/views/thread/create.blade.php
@extends('layouts.front')

@section('heading')
    Create Thread
@endsection

@section('content')

    @include('layouts.includes.error')

    @include('layouts.includes.success')

    <form action="{{ route('thread.store') }}" method="post" role="form" style="padding-bottom: 20px;">

        {{ csrf_field() }}

        <div class="form-group">
            <label for="subject">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ old('subject') }}" placeholder="Input...">
        </div>

        <div class="form-group">
            <label for="tag">Tags</label>
            <select class="form-control" name="tags[]" id="tag" multiple>

                @foreach($tags as $tag)

                    <option value="{{ $tag->id }}">{{ $tag->name }}</option>

                @endforeach

            </select>
        </div>

        <div class="form-group">
            <label for="thread">Thread</label>
            <textarea name="thread" id="thread" class="form-control" cols="30" rows="5">{{ old('thread') }}</textarea>
        </div>

        {{--<div class="form-group">--}}
            {{--{!! NoCaptcha::renderJs() !!}--}}
            {{--{!! NoCaptcha::display() !!}--}}
        {{--</div>--}}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>

@endsection

@section('js')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.6/js/standalone/selectize.min.js"></script>

    <script>
        $(function () {

            $('#tag').selectize();

        })
    </script>

@endsection

resources/views/thread/edit.blade.php
@extends('layouts.front')

@section('heading')
    Create Thread
@endsection

@section('content')

    @include('layouts.includes.error')

    @include('layouts.includes.success')

    <form action="{{ route('thread.update', $thread->id) }}" method="post" role="form" style="padding-bottom: 20px;">

        {{ csrf_field() }}
        {{ method_field('PUT') }}

        <div class="form-group">
            <label for="subject">Subject</label>
            <input type="text" class="form-control" name="subject" id="subject" value="{{ $thread->subject }}" placeholder="Input...">
        </div>

        <div class="form-group">
            <label for="type">Type</label>
            <input type="text" class="form-control" name="type" id="type" value="{{ $thread->type }}" placeholder="Input...">
        </div>

        <div class="form-group">
            <label for="thread">Thread</label>
            <textarea name="thread" id="thread" class="form-control" cols="30" rows="10">{{ $thread->thread }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
    </form>

@endsection

resources/views/thread/index.blade.php
@extends('layouts.front')

@section('heading')
    Threads
@endsection

@section('content')

    @include('thread.includes.thread-list')

@endsection

resources/views/thread/single.blade.php
@extends('layouts.front')

@section('heading')

    @include('layouts.includes.error')

    @include('layouts.includes.success')

    {{ $thread->subject }}

@endsection

@section('content')

    <div class="thread-details">
        {!! \Michelf\Markdown::defaultTransform($thread->thread) !!}
    </div>

    <br>

    @if(auth()->check())

        @if(auth()->user()->id == $thread->user_id)

            <div class="actions">

                <a href="{{ route('thread.edit', $thread->id) }}" class="btn btn-info btn-sm">Edit</a>

                <form action="{{ route('thread.destroy', $thread->id) }}" method="POST" role="form" class="delete-form">

                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}

                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">

                </form>

            </div>

            <br><br>

        @endif

    @endif

    {{--Answer/Comment--}}

    <h4>Comments</h4>

    @foreach($thread->comments as $comment)

        <div class="comment-list">

        <h4>{{ $comment->body }}</h4>

        <lead>{{ $comment->user->name }}</lead>

        @if(auth()->user()->id == $comment->user_id)

            <div class="actions">

                <button class="btn btn-sm btn-default" id="{{ $comment->id }}-count">
                    {{ $comment->likes()->count() }}
                </button>
                <span class="btn btn-sm btn-default {{ $comment->isLiked() ? 'liked' : '' }}" onclick="likeIt('{{ $comment->id }}', this)">
                    <span class="fa fa-heart"></span>
                </span>

                <a class="btn btn-primary btn-sm" data-toggle="modal" href="#{{ $comment->id }}">Edit</a>
                <div class="modal fade" id="{{ $comment->id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                                </button>
                                <h4 class="modal-title">Edit Comment</h4>
                            </div>
                            <div class="modal-body">

                                <div class="comment-form">
                                    <form action="{{ route('comment.update', $comment->id) }}" method="post" role="form">

                                        {{ csrf_field() }}
                                        {{ method_field('PUT') }}

                                        <div class="form-group">
                                            <input type="text" class="form-control" name="body" id="body" value="{{ $comment->body }}">
                                        </div>

                                        <button type="submit" class="btn btn-primary">Comment</button>
                                    </form>
                                </div>

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="button" class="btn btn-primary">Save changes</button>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->

                <form action="{{ route('comment.destroy', $comment->id) }}" method="POST" role="form" class="delete-form">

                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}

                    <input type="submit" class="btn btn-sm btn-danger" value="Delete">

                </form>

            </div>

        </div>

        @endif

        <br><br>

        <button class="btn btn-sm btn-default float-left" onclick="toggleReply('{{ $comment->id }}')">
            Reply
        </button>

        @if(!empty($thread->solution))

            @if($thread->solution == $comment->id)
                <button class="btn btn-primary btn-sm float-right">Solution</button>
            @endif

        @else

            {{--@if(auth()->check())--}}

                {{--@if($thread->user_id == auth()->user()->id)--}}

                    {{--<form action="{{ route('markAsSolution') }}" method="post">--}}
                        {{--{{ csrf_field() }}--}}
                        {{--<input type="hidden" name="threadId" value="{{ $thread->id }}">--}}
                        {{--<input type="hidden" name="solutionId" value="{{ $comment->id }}">--}}
                        {{--<input type="submit" class="btn btn-success btn-sm float-right" name="{{ $comment->id }}" id="{{ $comment->id }}" value="Mark as solution">--}}
                    {{--</form>--}}

                    @can('update',$thread)
                        <div id="markItSolution" class="btn btn-success float-right" onclick="markAsSolution('{{ $thread->id }}', '{{ $comment->id }}', this)">
                            Mark as solution
                        </div>
                    @endcan

                {{--@endif--}}

            {{--@endif--}}

        @endif

        <br>
        <hr>

        {{--reply form--}}

        <div class="reply-form-{{ $comment->id }} d-none">
            <form action="{{ route('replycomment.store', $comment->id) }}" method="post" role="form">

                {{ csrf_field() }}

                <legend>Reply</legend>

                <div class="form-group">
                    <input type="text" class="form-control" name="body" id="body" placeholder="Reply...">
                </div>

                <button type="submit" class="btn btn-primary">Reply</button>
            </form>
        </div>

        {{--reply to comment--}}

        @if($comment->comments->count() > 0)

            <h6>Replies to comment {{ $comment->id }}</h6>

            @foreach($comment->comments as $reply)

                <div class="small well text-info reply-list" style="margin-left:40px">
                    <p style="font-size: 15px;">{{ $reply->body }}</p>
                    <lead> by {{ $reply->user->name }}</lead>

                    <br>

                    <div class="actions">

                        <a class="btn btn-primary btn-sm" data-toggle="modal" href="#{{ $reply->id }}">Edit</a>
                        <div class="modal fade" id="{{ $reply->id }}">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
                                        </button>
                                        <h4 class="modal-title">Edit Reply</h4>
                                    </div>
                                    <div class="modal-body">

                                        <div class="comment-form">
                                            <form action="" method="post" role="form">

                                                {{ csrf_field() }}
                                                {{ method_field('PUT') }}

                                                <div class="form-group">
                                                    <input type="text" class="form-control" name="body" id="body" value="{{ $comment->body }}">
                                                </div>

                                                <button type="submit" class="btn btn-primary">Reply</button>
                                            </form>
                                        </div>

                                    </div>

                                </div><!-- /.modal-content -->
                            </div><!-- /.modal-dialog -->
                        </div><!-- /.modal -->

                        <form action="" method="POST" role="form" class="delete-form">

                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}

                            <input type="submit" class="btn btn-sm btn-danger" value="Delete">

                        </form>

                    </div>

                </div>

                <br>

                <hr>

            @endforeach

        @endif

    @endforeach

    
    <div class="comment-form">
        <form action="{{ route('threadcomment.store', $thread->id) }}" method="post" role="form">

            {{ csrf_field() }}

            <legend>Comment</legend>

            <div class="form-group">
                <input type="text" class="form-control" name="body" id="body" placeholder="Input...">
            </div>

            <button type="submit" class="btn btn-primary">Comment</button>
        </form>
    </div>

@endsection

@section('js')

    <script>

        function toggleReply(commentId) {
            $('.reply-form-' +commentId).toggleClass('d-none');
        }

        function markAsSolution(threadId, solutionId, elem) {
            var csrfToken = '{{ csrf_token() }}';
            $.post('{{ route('markAsSolution') }}', {solutionId: solutionId, threadId: threadId, _token: csrfToken}, function (data) {
                // console.log(data);
                $(elem).text('Solution');
            });

        }

        function likeIt(commentId, elem) {
            var csrfToken = '{{ csrf_token() }}';
            var likesCount = parseInt($('#'+commentId+"-count").text());
            $.post('{{ route('toggleLike') }}', {commentId: commentId, _token: csrfToken}, function (data) {
                console.log(data);
                // $(elem).css({color:'red'});
                if (data.message === 'liked'){
                    $(elem).addClass('liked');
                    $('#'+commentId+"-count").text(likesCount+1);
                }
                else{
                    $('#'+commentId+"-count").text(likesCount-1);
                    $(elem).removeClass('liked');
                }
            });

        }

    </script>

@endsection